spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.googlemail.com
    port: 587
    username: your mail id
    password: your password
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
          debug: true
